apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000       # Service Cluster IP port
      targetPort: 9000 # Pod port
      nodePort: 30082  # Mapped to your hostPort 8082